project_id = "bfwvjhrokucqjcbeufwk"

[functions.calendar-oauth]
verify_jwt = false

[functions.calendar-sync]
verify_jwt = true

[functions.send-invoice]
verify_jwt = false

[functions.create-course-checkout]
verify_jwt = false

[functions.r2-upload]
verify_jwt = true

[functions.r2-delete]
verify_jwt = true

[functions.r2-presigned-url]
verify_jwt = true
